### PR TITLE
build: Move dependencies to docs section

### PR DESCRIPTION
**Pull request by hpohekar**
closes https://github.com/ansys/pyfluent/issues/3420

Move dependencies to docs section.

### CODE REVIEW

**Comment by mkundu1** [comment]
Do we want the optional package `ansys-fluent-core[examples]`?

cc: @seanpearsonuk

**Comment by seanpearsonuk** [comment]
> Do we want the optional package `ansys-fluent-core[examples]`?
> 
> cc: @seanpearsonuk

I think so, but I'm happy to hear any points of view.

**Comment by hpohekar** [comment]
> Do we want the optional package `ansys-fluent-core[examples]`?
> 
> cc: @seanpearsonuk

@mkundu1 We already have `examples` package in `extras`.

**Comment by seanpearsonuk** [comment]
> > Do we want the optional package `ansys-fluent-core[examples]`?
> > cc: @seanpearsonuk
> 
> @mkundu1 We already have `examples` package in `extras`.

That is the thing that @mkundu1 is referring to.

**Comment by hpohekar** [comment]
> > > Do we want the optional package `ansys-fluent-core[examples]`?
> > > cc: @seanpearsonuk
> > 
> > 
> > @mkundu1 We already have `examples` package in `extras`.
> 
> That is the thing that @mkundu1 is referring to.

Thanks for the clarification.

**Review by mkundu1 — APPROVED** [review]

**Review by prmukherj — APPROVED** [review]

**Pull request merged**
