### PR TITLE
Support SolverLite mode

### PR DESCRIPTION
**Pull request by hpohekar**
Now we can use `solver-lite` mode.

```
>>> import ansys.fluent.core as pyfluent
>>> session = pyfluent.launch_fluent(mode="solver-lite", precision="double", processor_count=2, lightweight_mode=True, show_gui=True)

>>> session.__class__
<class 'ansys.fluent.core.session_solver_lite.SolverLite'>

>>> from ansys.fluent.core import examples
>>> import_file_name = examples.download_file("mixing_elbow.msh.h5", "pyfluent/mixing_elbow")
File already exists. File path:
C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\mixing_elbow.msh.h5

>>> session.file.read(file_name=import_file_name, file_type="mesh", lightweight_setup=True)   
Fast-loading "D:\ANSYSDev\vNNN\fluent\fluent24.2\\addons\afd\lib\hdfio.bin"
Done.
Multicore SMT processors detected. Processor affinity set!

Reading from AAPQ13pUvWxQtxN:"C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\mixing_elbow.msh.h5" in NODE0 mode ...
  Reading mesh info ...
       17822 cells,     1 cell zone  ...
          17822 mixed cells,  zone id: 87
       91581 faces,     7 face zones ...
           2168 polygonal wall faces,  zone id: 34
            268 polygonal wall faces,  zone id: 33
            155 polygonal pressure-outlet faces,  zone id: 32
            152 polygonal velocity-inlet faces,  zone id: 31
             55 polygonal velocity-inlet faces,  zone id: 30
           2001 polygonal symmetry faces,  zone id: 29
          86782 mixed interior faces,  zone id: 89
       66417 nodes,     3 node zones ...

Building...
     mesh
        distributing mesh
                parts..,
                faces..,
                nodes..,
                cells..,
     materials,
     interface,
     domains,
     zones,
        Skipping thread 20 of domain 1 (not referenced by grid).
        Skipping thread 21 of domain 1 (not referenced by grid).
        Skipping thread 22 of domain 1 (not referenced by grid).
        Skipping thread 23 of domain 1 (not referenced by grid).
        Skipping thread 24 of domain 1 (not referenced by grid).
        Skipping thread 25 of domain 1 (not referenced by grid).
        Skipping thread 26 of domain 1 (not referenced by grid).
        Skipping thread 27 of domain 1 (not referenced by grid).
        Skipping thread 28 of domain 1 (not referenced by grid).
        wall-elbow
        wall-inlet
        outlet
        cold-inlet
        hot-inlet
        symmetry-xyplane
        interior--elbow-fluid
        elbow-fluid
     parallel,
Done.

Only case settings are read, in order to review and/or modify the settings.
It is not possible to manipulate the mesh or run calculations unless you read the entire case file.
True
>>> 
>>> dir(session)
['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__
', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_batch_ops_service', '_build_from_fluent_connection', '_field_dat
a_service', '_lck', '_monitors_service', '_pim_methods', '_preferences', '_reduction_service', '_remote_file_handler', '_root', '_se_service', '_settings_root', '_settings_service', '_sync_from_future', '_system_coupling', '_tui', '
_tui_service', '_version', '_workflow', '_workflow_se', 'build_from_fluent_connection', 'connection_properties', 'create_from_server_info_file', 'current_parametric_study', 'datamodel_events', 'datamodel_service_se', 'datamodel_serv
ice_tui', 'error_state', 'events_manager', 'events_service', 'execute_tui', 'exit', 'field_data', 'field_data_streaming', 'field_info', 'file', 'fluent_connection', 'force_exit', 'force_exit_container', 'get_fluent_version', 'health
_check_service', 'id', 'journal', 'mesh', 'monitors_manager', 'parallel', 'parameters', 'parametric_studies', 'preferences', 'read_case', 'read_case_lightweight', 'reduction', 'report', 'results', 'rp_vars', 'scheme_eval', 'server',
 'settings_service', 'setup', 'solution', 'start_journal', 'stop_journal', 'svar_data', 'svar_info', 'svar_service', 'switch_to_full_solver', 'system_coupling', 'transcript', 'tui', 'version', 'workflow', 'write_case']

>>> full_solver_session = session.switch_to_full_solver()

>>> dir(full_solver_session)
['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__
', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_batch_ops_service', '_build_from_fluent_connection', '_field_dat
a_service', '_lck', '_monitors_service', '_pim_methods', '_preferences', '_reduction_service', '_remote_file_handler', '_root', '_se_service', '_settings_root', '_settings_service', '_sync_from_future', '_system_coupling', '_tui', '
_tui_service', '_version', '_workflow', '_workflow_se', 'build_from_fluent_connection', 'connection_properties', 'create_from_server_info_file', 'current_parametric_study', 'datamodel_events', 'datamodel_service_se', 'datamodel_serv
ice_tui', 'error_state', 'events_manager', 'events_service', 'execute_tui', 'exit', 'field_data', 'field_data_streaming', 'field_info', 'file', 'fluent_connection', 'force_exit', 'force_exit_container', 'get_fluent_version', 'health
_check_service', 'id', 'journal', 'mesh', 'monitors_manager', 'parallel', 'parameters', 'parametric_studies', 'preferences', 'read_case', 'read_case_lightweight', 'reduction', 'report', 'results', 'rp_vars', 'scheme_eval', 'server',
 'settings_service', 'setup', 'solution', 'start_journal', 'stop_journal', 'svar_data', 'svar_info', 'svar_service', 'system_coupling', 'transcript', 'tui', 'version', 'workflow', 'write_case']

>>> full_solver_session.__class__
<class 'ansys.fluent.core.session_solver.Solver'>

>>> full_solver_session.file.read_case(file_name=import_file_name) 
True

>>> full_solver_session.exit()
>>>
```

### CODE REVIEW

**Comment by seanpearsonuk** [comment]
@hpohekar if I start solver lite, it's going to give me a regular solver session, right? Even in 24R1, Fluent still doesn't offer a separate "lite" launch more AFAIK.

**Comment by hpohekar** [comment]
> @hpohekar if I start solver lite, it's going to give me a regular solver session, right? Even in 24R1, Fluent still doesn't offer a separate "lite" launch more AFAIK.

Yes. If we start solver lite we get an instance of `ansys.fluent.core.session_solver_lite.SolverLite` with `switch_to_full_solver` method which is not available on regular solver session (`ansys.fluent.core.session_solver.Solver`).

**Comment by seanpearsonuk** [comment]
> switch_to_full_solver

And `switch_to_full_solver` has no effect itself, given that solver and lite solver are the same thing? Maybe we should just hide this feature?

**Comment by hpohekar** [comment]
> > switch_to_full_solver
> 
> And `switch_to_full_solver` has no effect itself, given that solver and lite solver are the same thing? Maybe we should just hide this feature?

@seanpearsonuk Yes, I agree. We will just remove it from documentation. Thank you.

**Comment by hpohekar** [comment]
https://github.com/ansys/pyfluent/pull/2285

**Pull request closed without merging**
