### PR TITLE
Update python version

### PR DESCRIPTION
**Pull request by hpohekar**
changed python 3.8 to 3.11

### CODE REVIEW

**Comment by mkundu1** [comment]
image
There seem to be more places where Python 3.7 is mentioned, Can you please update those too?

**Comment by raph-luc** [comment]
Changed the remaining places mentioning Python 3.7, and updated the FAQ to use version v232, as that is the first ANSYS release that includes a Python version newer than 3.7 (it includes Python 3.10).

**Comment by raph-luc** [comment]
Related issue: https://github.com/ansys/pyfluent/issues/1590

**Comment by hpohekar** [comment]
> image There seem to be more places where Python 3.7 is mentioned, Can you please update those too?

Yes, sure. Thank you.

**Comment by hpohekar** [comment]
> Changed the remaining places mentioning Python 3.7, and updated the FAQ to use version v232, as that is the first ANSYS release that includes a Python version newer than 3.7 (it includes Python 3.10).

@raph-luc  Thank you..

**Review by prmukherj — APPROVED** [review]

**Review by seanpearsonuk — APPROVED** [review]

**Pull request merged**
