### PR TITLE
docs: Start all custom exception class docstring with Is raised...

### PR DESCRIPTION
**Pull request by hpohekar**
Replaced "Provides the error ...." with "Raised ...." in all custom exception classes docstring.

### CODE REVIEW

**Review by prmukherj — APPROVED** [review]

**Comment by mkundu1** [comment]
"Raised when ..." sounds better.

The build-in exceptions follows the same format - https://docs.python.org/3/library/exceptions.html#concrete-exceptions.

**Review by seanpearsonuk — APPROVED** [review]

**Comment by PipKat** [comment]
> "Raised when ..." sounds better.
> 
> The built-in exceptions follow the same format - https://docs.python.org/3/library/exceptions.html#concrete-exceptions.

I'd be onboard with using "Raised" and following the Python org format.

**Comment by seanpearsonuk** [comment]
> > "Raised when ..." sounds better.
> > The built-in exceptions follow the same format - https://docs.python.org/3/library/exceptions.html#concrete-exceptions.
> 
> I'd be OK with using "Raised" to follow the Python org format, although I'd prefer using "Raises" to be consistent with our own docstring style.

Yes "Raised when

> > "Raised when ..." sounds better.
> > The built-in exceptions follow the same format - https://docs.python.org/3/library/exceptions.html#concrete-exceptions.
> 
> I'd be OK with using "Raised" to follow the Python org format, although I'd prefer using "Raises" to be consistent with our own docstring style.

Yes, _Raised when_ is our intention here and _Is raised when_ was meant as a compromise. I don't know how to start a docstring for an exception class with _Raises_; @PipKat?

**Comment by PipKat** [comment]
> > > "Raised when ..." sounds better.
> > > The built-in exceptions follow the same format - https://docs.python.org/3/library/exceptions.html#concrete-exceptions.
> > 
> > 
> > I'd be OK with using "Raised" to follow the Python org format, although I'd prefer using "Raises" to be consistent with our own docstring style.
> 
> Yes "Raised when
> 
> > > "Raised when ..." sounds better.
> > > The built-in exceptions follow the same format - https://docs.python.org/3/library/exceptions.html#concrete-exceptions.
> > 
> > 
> > I'd be OK with using "Raised" to follow the Python org format, although I'd prefer using "Raises" to be consistent with our own docstring style.
> 
> Yes, _Raised when_ is our intention here and _Is raised when_ was meant as a compromise. I don't know how to start a docstring for an exception class with _Raises_; @PipKat?

@seanpearsonuk Point taken. To use "Raises" we'd need to rewrite as this: "Raises the error that occurs when ...." I know this seems wordy and might possibly cause line length issues for some error classes.  However, without the brief description including what is raised (an error), it isn't clear on its own. I know that the type of error appears after the class name, so I won't waste anymore of your time. Go ahead and use whatever you decide is best.

**Comment by hpohekar** [comment]
@mkundu1 @seanpearsonuk @prmukherj 

We have used "Raised when..." everywhere.

**Pull request merged**
