### PR TITLE
Expose base class in settings doc

### PR DESCRIPTION
**Pull request by hpohekar**
Exposed base class in settings doc.

image

### CODE REVIEW

**Comment by seanpearsonuk** [comment]
I'm noticing a pre-existing issue regarding broken links in the dev docs which makes it difficult to check the results of these changes. @hpohekar

**Comment by hpohekar** [comment]
> I'm noticing a pre-existing issue regarding broken links in the dev docs which makes it difficult to check the results of these changes. @hpohekar

@seanpearsonuk This change will be effective after running nightly doc build. In description I have pasted screenshot of local doc build. Can you please mention the broken links ?

**Comment by seanpearsonuk** [comment]
> > I'm noticing a pre-existing issue regarding broken links in the dev docs which makes it difficult to check the results of these changes. @hpohekar
> 
> @seanpearsonuk This change will be effective after running nightly doc build. In description I have pasted screenshot of local doc build. Can you please mention the broken links ? The linked issue does not describe any information related to broken links. Thanks.

@hpohekar 
Thanks for pasting the image.
You'll see a lot of things not clickable in api/solver/settings.html and api/solver/index.html.

**Review by seanpearsonuk — APPROVED** [review]

**Comment by seanpearsonuk** [comment]
@hpohekar I can add another separate issue about the dev doc build, but please ignore it.

**Review by prmukherj — APPROVED** [review]

**Pull request merged**
