### PR TITLE
feat: Replace scheme call in get_vector_fields

### PR DESCRIPTION
**Pull request by hpohekar**
closes https://github.com/ansys/pyfluent/issues/3512

Replaced scheme call in `get_vector_fields()`

### CODE REVIEW

**Comment by prmukherj** [comment]
@hpohekar, I think we can address all the scheme calls together in a PR? We can update the proto files as required for this. What do you think?

**Comment by seanpearsonuk** [comment]
> @hpohekar, I think we can address all the scheme calls together in a PR? We can update the proto files as required for this. What do you think?

@prmukherj code change so far looks potentially OK (as far as I can tell). Isn't this approach OK, gradually removing the Scheme dependencies?

**Comment by prmukherj** [comment]
> > @hpohekar, I think we can address all the scheme calls together in a PR? We can update the proto files as required for this. What do you think?
> 
> @prmukherj code change so far looks potentially OK (as far as I can tell). Isn't this approach OK, gradually removing the Scheme dependencies?

Yes @seanpearsonuk, should be fine. Just wanted to take a look into all the calls once and decide, that's all.

**Review by mkundu1 — APPROVED** [review]

**Review by prmukherj — APPROVED** [review]

**Comment by prmukherj** [comment]
Tested visualization with this update and seems to run correctly. So no effect.

**Pull request merged**
